export const activityListAllYear = [
  "Nudazyti figurele",
  "Pabegioti",
  "Pazaisti zaidimus",
  "Iskepti nauja recepta",
  "Pasicaikscioti",
  "Arduino",
  "Diena su Domu",
  "Paziureti kursa",
  "Nuvaziuoti kur nebuves",
  "Organizuoti filmų vakarą",
  "Aplankyti muziejų ar galeriją",
  "Eksperimentuoti su fotografija, naujas technikos",
  "Sudėlioti LEGO",
  "Tapybą",
  "Atlikti mažą mokslinį eksperimentą namuose",
  "Pasigaminti naują kokteilį ar gėrimą",
  "Aplankyti seną dvarą ar pilį",
  "Apsilankyti vietiniame teatre ar koncerte",
  "Aplankyti naują parką ar gamtos taką netoli namų",
  "Dalyvauti vietiniame renginyje",
  "Suplanuoti dienos kelionę į netolimą miestelį",
  "Sukurti 3d modeli mena",
  "Sumontuoti video",
  "Žaisti stalo žaidimus su draugais ar šeima",
  "Daryti smegenų mankštą su galvosūkiais",
  "Skaityti knygą ar klausytis audioknygos",
  "Pasimokinti naujas programavimo idejas technologijas",
];

export const activityListSummer = [
  "Pasivazineti paspirtuku",
  "Pasivazineti dviraciu",
  "Paskraidyti dronu",
  "Paplaukioti kajaku",
  "Issimaudyti",
  "Pasivazineti kartingu",
  "Pasportuoti lauke",
  "Pažvelgti į žvaigždes su teleskopu",
  "Lauko kino sensas",
  "Rinkti miško uogas ar vaisius",
  "Surengti fotografijos ekskursiją",
  "Sutikti ryta prie ežero arba gamtoje",
  "Žaisti lauko badmintoną arba frisbee",
  "Paspardyti kamuoli",
  "Pmetyti krepsini",
  "Stoviklauti",
  "Naktinė fotosesija su žibintais arba prožektoriais",
  "Pajieskos metalo detektoriu",
];

export const activityListWinter = [
  "Čiuožti pačiūžomis ledo stadione",
  "Aplankyti kalėdinę mugę arba žiemos festivalį",
  "Stebėti snieguotą kraštovaizdį ir daryti nuotraukas",
  "Organizuoti filmų vakarą su žiemos tematika",
  "Pagaminti ziemines dekoracijas",
];

export const relaxationActivities = [
  "Meditacija arba kvėpavimo pratimai",
  "Savimasažas arba naudojant masažuoklį",
  "Aromaterapijos seansas su eteriniais aliejais",
  "Šiltos vonios su jūros druskomis arba vonios burbulais",
  "Raminanti muzika arba garsų terapija (pvz., gamtos garsai, binaural beats)",
  "Joga arba švelnūs tempimo pratimai",
  "Vaistažolių arbatos gėrimo ritualas",
  "Raumenų atpalaidavimo pratimai",
  "Įsivaizdavimo (vizualizacijos) pratimai",
  "Skaitymas ramioje aplinkoje",
  "Spalvinimas arba mandalų piešimas",
  "Dienoraščio rašymas savirefleksijai",
  "Klausytis audioknygų ar poezijos įrašų",
  "Žvakių ar smilkalų deginimas atsipalaidavimui",
  "Aplankyti gamtą ir mėgautis grynu oru",
  "Raminantis kūno šveitimas arba drėkinimo procedūra",
  "Pasivaikščiojimas ramioje vietoja ežero, upes, parke ar miške",
  "Raumenų atpalaidavimas su šilumos pagalvėlėmis",
  "Tempimo rutina prieš miegą geresniam poilsiui",

  "Klausytis meditacinės muzikos arba garso terapijos seanso",
  "Žiūrėti raminančius dokumentinius filmus apie gamtą",
  "Klausytis gamtos garsų (pvz., lietaus, bangų) per internetą arba programas",
  "Naudoti meditacinius rutulius arba kitus atsipalaidavimo įrankius",
  "Rašyti teigiamus afirmacijas",
  "Kurti kūrybinius projektus, pvz., tapybą ar keramiką, atsipalaidavimo tikslais",
  "Išbandyti švelnius kvėpavimo pratimus su fokusavimu į kiekvieną kvėpavimą",
  "Klausyti raminančios muzikos ir daryti šviesos masažą sau",
];

export const booksToRead = [
  "ORM Simpfony",
  "MongoDB",
  "Simpfony",
  "Linux",
  "SQL",
  "React",
  "PHP",
  "Node.js",
  "Express.js",
  "JavaScript",
  "TypeScritp",
  "ORM MongoDB",
  "API Design",
  "Testing PHP",
  "Testing React",
  "Security",
];
